# Конфигурация для продвинутых фичей (on-chain метрики и sentiment анализ)

# API ключи (замените на реальные)
api_keys:
  # Glassnode API для on-chain метрик
  # Получить: https://glassnode.com/
  glassnode_api_key: "demo"  # Замените на реальный ключ
  
  # Twitter API для social sentiment
  # Получить: https://developer.twitter.com/
  twitter_bearer_token: ""  # Замените на реальный токен
  
  # News API для анализа новостей
  # Получить: https://newsapi.org/
  news_api_key: ""  # Замените на реальный ключ
  
  # CoinMetrics API для дополнительных метрик
  coinmetrics_api_key: ""  # Опционально

# Параметры on-chain анализа
onchain_settings:
  # Минимальная сумма для определения "whale movement"
  whale_threshold_btc: 100.0
  whale_threshold_eth: 1000.0
  
  # Периоды для rolling статистик
  lookback_periods: [7, 14, 30]
  
  # Веса для composite on-chain score
  composite_weights:
    whale_movements: 0.2
    exchange_flows: 0.3
    network_activity: 0.2
    hodler_behavior: 0.3
  
  # Параметры кеширования (часы)
  cache_duration_hours: 1

# Параметры sentiment анализа
sentiment_settings:
  # Источники sentiment данных
  sources:
    fear_greed: true
    social_media: true
    news: true
    bybit_opportunities: true
    funding_rates: true
  
  # Веса для composite sentiment score
  composite_weights:
    fear_greed: 0.30
    social_sentiment: 0.20
    news_sentiment: 0.20
    bybit_opportunities: 0.15
    funding_rates: 0.15
  
  # Параметры анализа текста
  text_analysis:
    positive_keywords: 
      - "bull"
      - "bullish" 
      - "rise"
      - "gain"
      - "positive"
      - "up"
      - "surge"
      - "rally"
      - "boom"
      - "moon"
      - "pump"
    
    negative_keywords:
      - "bear"
      - "bearish"
      - "fall"
      - "loss"
      - "negative"
      - "down"
      - "crash"
      - "dump"
      - "decline"
      - "correction"
      - "dip"
  
  # Параметры кеширования
  cache_duration:
    fear_greed_hours: 6
    bybit_opportunities_hours: 2
    social_sentiment_hours: 1
    news_sentiment_hours: 4

# Параметры корреляционного анализа
correlation_settings:
  # Окна для расчета корреляций
  windows: [14, 30, 60]
  
  # Минимальный порог корреляции для значимости
  significance_threshold: 0.3
  
  # Лаги для lead/lag анализа
  lag_periods: [1, 3, 7, 14]

# Параметры feature engineering
feature_engineering:
  # Максимальное количество on-chain фичей
  max_onchain_features: 50
  
  # Максимальное количество sentiment фичей  
  max_sentiment_features: 30
  
  # Максимальное количество correlation фичей
  max_correlation_features: 20
  
  # Методы заполнения пропусков
  fill_methods:
    onchain: "ffill"  # forward fill
    sentiment: "interpolate"
    correlation: "zero"
  
  # Нормализация фичей
  normalization:
    method: "robust"  # robust, standard, minmax
    clip_outliers: true
    outlier_threshold: 3.0  # стандартных отклонений

# Параметры производительности
performance:
  # Многопоточность
  max_workers: 4
  
  # Размер батча для обработки
  batch_size: 1000
  
  # Таймауты для API запросов (секунды)
  api_timeouts:
    glassnode: 10
    twitter: 15
    news: 10
    bybit: 15
    default: 10
  
  # Ограничения скорости API
  rate_limits:
    glassnode_per_minute: 10
    twitter_per_hour: 300
    news_per_day: 1000

# Мониторинг и логирование
monitoring:
  # Уровень логирования
  log_level: "INFO"
  
  # Метрики для отслеживания
  track_metrics:
    - "api_response_time"
    - "feature_generation_time"
    - "cache_hit_rate"
    - "data_quality_score"
  
  # Алерты
  alerts:
    api_failure_threshold: 3  # подряд неудачных запросов
    data_staleness_hours: 24  # максимальный возраст данных
    correlation_break_threshold: 0.5  # резкое изменение корреляций

# Стратегии обработки ошибок
error_handling:
  # Количество повторных попыток
  retry_attempts: 3
  
  # Задержка между попытками (секунды)
  retry_delay: 5
  
  # Fallback стратегии
  fallback_strategies:
    onchain_data: "synthetic"  # synthetic, historical, skip
    sentiment_data: "neutral"  # neutral, historical, skip
    api_failure: "cache"       # cache, synthetic, skip
  
  # Минимальные требования к данным
  minimum_data_requirements:
    onchain_days: 7
    sentiment_days: 3
    correlation_window: 14

# Настройки для разных криптовалют
symbol_specific:
  BTC:
    whale_threshold: 100.0
    focus_metrics: ["whale_movements", "exchange_flows", "hodler_behavior"]
    sentiment_weight: 0.4
    
  ETH:
    whale_threshold: 1000.0
    focus_metrics: ["network_activity", "exchange_flows", "social_sentiment"]
    sentiment_weight: 0.5
    
  # Настройки по умолчанию для других монет
  default:
    whale_threshold: 50.0
    focus_metrics: ["exchange_flows", "sentiment"]
    sentiment_weight: 0.6 