advanced_features:
  api_keys:
    glassnode_api_key: demo
    news_api_key: ''
    twitter_bearer_token: ''
  enabled: true
  sentiment:
    bybit_opportunities: true
    cache_duration_hours: 2
    weights:
      gainers_ratio: 0.3
      market_sentiment: 0.4
      trending_ratio: 0.3
alerts:
  enabled: true
  sentiment_alerts:
    extreme_fear_threshold: 0.2
    extreme_greed_threshold: 0.8
    regime_change_alert: true
  trading_alerts:
    high_confidence_signal: 0.8
    low_confidence_warning: 0.4
    significant_drawdown: 0.05
backtesting:
  commission: 0.001
  end_date: '2024-12-31'
  initial_balance: 10000
  metrics:
  - total_return
  - sharpe_ratio
  - max_drawdown
  - win_rate
  - profit_factor
  - total_trades
  - avg_trade_duration
  - sentiment_accuracy
  slippage: 0.0005
  start_date: '2024-01-01'
confidence_scorer:
  enabled: true
  thresholds:
    cci_overbought: 100
    cci_oversold: -100
    high_confidence: 0.8
    min_confidence: 0.65
    rsi_overbought: 70
    rsi_oversold: 30
    williams_r_overbought: -20
    williams_r_oversold: -80
  weights:
    indicator_agreement: 0.22
    market_regime: 0.1
    sentiment_confirmation: 0.05
    signal_strength: 0.2
    volatility_factor: 0.15
    volume_confirmation: 0.28
entry_rules:
  min_confidence: 0.6
  min_indicators_agreement: 6
  sentiment_filters:
    buy_requirements:
      bullish_regime_bonus: 0.1
      min_sentiment_score: 0.4
    enabled: true
    sell_requirements:
      bearish_regime_bonus: 0.1
      max_sentiment_score: 0.6
  volatility_filters:
    max_atr_percentage: 5.0
    min_volume_ratio: 0.5
exit_rules:
  exit_on_low_confidence: true
  exit_on_opposite_signal: true
  min_exit_confidence: 0.5
  sentiment_exits:
    early_exit_on_sentiment_change: true
    enabled: true
    favorable_sentiment_threshold: 0.7
    hold_on_favorable_sentiment: true
    sentiment_change_threshold: 0.3
feature_engineering:
  enabled: true
  importance_threshold: 0.003
  max_features: 50
  prediction_horizons:
    15m: 10
    1d: 5
    1h: 8
    4h: 6
    5m: 12
  technical_indicators:
    periods:
      long:
      - 50
      - 100
      medium:
      - 20
      - 30
      short:
      - 5
      - 10
      - 14
indicators:
  15m:
  - macd
  - obv
  - vwap
  1h:
  - rsi
  - obv
  - vwap
  5m:
  - macd
  - obv
  - vwap
logging:
  level: INFO
  performance_monitoring:
    enabled: true
    log_confidence_distribution: true
    log_feature_importance: true
    log_model_performance: true
  sentiment_monitoring:
    alert_on_extreme_sentiment: true
    enabled: true
    log_regime_changes: true
    log_sentiment_changes: true
models:
  ensemble:
    class_balancing: balanced
    enabled: true
    lightgbm:
      class_weight: balanced
      force_col_wise: true
      learning_rate: 0.03
      max_depth: 10
      metric: auc
      n_estimators: 500
      n_jobs: -1
      num_leaves: 40
      objective: binary
      random_state: 42
    random_forest:
      class_weight: balanced
      max_depth: 25
      max_features: sqrt
      min_samples_leaf: 1
      min_samples_split: 2
      n_estimators: 400
      n_jobs: -1
      random_state: 42
    use_binary_classification: true
    xgboost:
      colsample_bytree: 0.85
      eval_metric: auc
      learning_rate: 0.03
      max_depth: 8
      n_estimators: 500
      n_jobs: -1
      random_state: 42
      scale_pos_weight: auto
      subsample: 0.85
modes:
  development:
    enhanced_logging: true
    paper_trading: true
    sentiment_simulation: true
  production:
    alert_notifications: true
    paper_trading: false
    real_sentiment_data: true
    strict_risk_management: true
performance:
  api_rate_limits:
    bybit_requests_per_minute: 20
    max_retries: 3
    retry_delay_seconds: 5
  cache_enabled: true
  cache_ttl_hours: 2
  max_workers: 4
risk_management:
  max_position_size: 0.02
  max_total_exposure: 0.1
  sentiment_adjustment:
    bearish_regime_multiplier: 0.7
    bullish_regime_multiplier: 1.3
    enabled: true
    high_confidence_multiplier: 1.2
    low_confidence_multiplier: 0.8
    neutral_regime_multiplier: 1.0
  stop_loss:
    atr_multiplier: 2.0
    default_percentage: 0.02
    enabled: true
    sentiment_adjustment: true
  take_profit:
    default_percentage: 0.04
    enabled: true
    sentiment_adjustment: true
    trailing_enabled: true
signal_generation:
  action_threshold: 0.65
  action_type_determination:
    buy_indicators:
    - price_above_sma_20
    - rsi_oversold_recovery
    - macd_bullish_crossover
    - positive_sentiment
    - bullish_regime
    sell_indicators:
    - price_below_sma_20
    - rsi_overbought
    - macd_bearish_crossover
    - negative_sentiment
    - bearish_regime
    use_sentiment_context: true
    use_technical_context: true
  binary_classification: true
  confidence_threshold: 0.7
  quality_filters:
    max_volatility_percentile: 90
    min_indicator_agreement: 0.65
    min_sentiment_stability: 0.5
    min_volume_confirmation: 0.6
symbols:
- BTCUSDT
- ETHUSDT
timeframes:
- 5m
- 15m
- 1h
