# УМНАЯ АДАПТИВНАЯ конфигурация системы торговли криптовалютами с ML
# Динамическая адаптация фильтров на основе рыночных условий
# ОБНОВЛЕНО на основе рекомендаций из JSON файлов

# Настройки сбора данных
data_collection:
  exchange: "binance"
  symbols: ["BTC/USDT", "ETH/USDT"]
  timeframes: ["5m", "15m", "1h"]
  limits:
    5m: 200000
    15m: 200000
    1h: 200000

# Параметры по таймфреймам
timeframe_params:
  5m:
    xgboost:
      n_estimators: 1000
      max_depth: 12
      learning_rate: 0.02
      subsample: 0.9
      colsample_bytree: 0.9
      reg_alpha: 0.01
      reg_lambda: 0.3
      min_child_weight: 1
      random_state: 42
      verbose: false
      n_jobs: -1
    random_forest:
      n_estimators: 500
      max_depth: 15
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 42
      n_jobs: -1
    lightgbm:
      n_estimators: 800
      max_depth: 10
      learning_rate: 0.05
      subsample: 0.9
      colsample_bytree: 0.9
      reg_alpha: 0.01
      reg_lambda: 0.3
      random_state: 42
      verbose: -1
      n_jobs: -1
    classification_threshold: 0.001
  15m:
    xgboost:
      n_estimators: 500
      max_depth: 10
      learning_rate: 0.03
      subsample: 0.9
      colsample_bytree: 0.9
      reg_alpha: 0.01
      reg_lambda: 0.3
      min_child_weight: 1
      random_state: 42
      verbose: false
      n_jobs: -1
    random_forest:
      n_estimators: 300
      max_depth: 12
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 42
      n_jobs: -1
    lightgbm:
      n_estimators: 500
      max_depth: 8
      learning_rate: 0.05
      subsample: 0.9
      colsample_bytree: 0.9
      reg_alpha: 0.01
      reg_lambda: 0.3
      random_state: 42
      verbose: -1
      n_jobs: -1
    classification_threshold: 0.001
  1h:
    xgboost:
      n_estimators: 500
      max_depth: 10
      learning_rate: 0.03
      subsample: 0.9
      colsample_bytree: 0.9
      reg_alpha: 0.01
      reg_lambda: 0.3
      min_child_weight: 1
      random_state: 42
      verbose: false
      n_jobs: -1
    random_forest:
      n_estimators: 300
      max_depth: 12
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 42
      n_jobs: -1
    lightgbm:
      n_estimators: 500
      max_depth: 8
      learning_rate: 0.05
      subsample: 0.9
      colsample_bytree: 0.9
      reg_alpha: 0.01
      reg_lambda: 0.3
      random_state: 42
      verbose: -1
      n_jobs: -1
    classification_threshold: 0.002

# Настройки бэктестинга
backtesting:
  enabled: true
  auto_run_after_training: true
  initial_capital: 10000
  commission: 0.001
  slippage: 0.0005
  position_size: 0.25
  min_confidence: 0.45
  trend_filter: false
  volatility_filter: false
  max_positions: 4
  adaptive_risk: true
  use_proper_train_test_split: true 